### ISSUE TITLE
Your password is showing

### ISSUE THREAD

**Issue by peterwwillis** [istresearch/json-transporter#15]
Is your pypi server password supposed to be in here?

https://github.com/istresearch/json-transporter/blob/master/.travis.yml

**Comment by madisonb** [comment]
That is a travis ci encrypted variable. Please see [here](https://docs.travis-ci.com/user/encryption-keys/) for more info.

**Comment by peterwwillis** [comment]
Nevermind, I didn't see the 'secure' part, my bad 😳
